import { Listing, NavItem, Stat, Equipment } from './types';

export const NAV_ITEMS: NavItem[] = [
  { label: 'Home', path: '/' },
  { label: 'Marketplace', path: '/marketplace' },
  { label: 'For Farmers', path: '/farmers' },
  { label: 'For Buyers', path: '/buyers' },
  { label: 'Equipment', path: '/equipment' },
  { label: 'Carbon Credits', path: '/carbon-credits' },
];

export const CROP_TYPES = [
  { id: 'paddy', name: 'Paddy (Rice)', icon: '🌾', residues: ['Straw', 'Stubble', 'Husk'] },
  { id: 'wheat', name: 'Wheat', icon: '🌿', residues: ['Straw', 'Husk', 'Chaff'] },
  { id: 'sugarcane', name: 'Sugarcane', icon: '🎋', residues: ['Bagasse', 'Trash', 'Tops'] },
  { id: 'cotton', name: 'Cotton', icon: '☁️', residues: ['Stalks', 'Shells', 'Lint Waste'] },
  { id: 'mustard', name: 'Mustard', icon: '🌼', residues: ['Stalks', 'Shells'] },
  { id: 'maize', name: 'Maize', icon: '🌽', residues: ['Stalks', 'Cobs', 'Husk'] },
  { id: 'groundnut', name: 'Groundnut', icon: '🥜', residues: ['Shells', 'Stalks'] },
  { id: 'soybean', name: 'Soybean', icon: '🫘', residues: ['Stalks', 'Pods'] },
];

export const INDIAN_STATES = [
  'Punjab', 'Haryana', 'Uttar Pradesh', 'Madhya Pradesh', 'Rajasthan',
  'Gujarat', 'Maharashtra', 'Karnataka', 'Andhra Pradesh', 'Tamil Nadu',
  'Bihar', 'West Bengal', 'Odisha', 'Chhattisgarh', 'Jharkhand',
];

export const BUYER_TYPES = [
  { id: 'bioenergy', name: 'Bioenergy Plant', icon: '⚡' },
  { id: 'packaging', name: 'Eco-Packaging', icon: '📦' },
  { id: 'biogas', name: 'Biogas / CBG', icon: '💨' },
  { id: 'compost', name: 'Compost & Fertilizer', icon: '🌱' },
  { id: 'ethanol', name: 'Ethanol Producer', icon: '🧪' },
  { id: 'other', name: 'Other', icon: '🏭' },
];

export const QUALITY_OPTIONS = [
  { id: 'Premium', name: 'Premium', description: 'Low moisture (<12%), no contamination', multiplier: 1.2 },
  { id: 'Standard', name: 'Standard', description: 'Normal moisture (12-18%)', multiplier: 1.0 },
  { id: 'Mixed', name: 'Mixed', description: 'Higher moisture (>18%) or mixed quality', multiplier: 0.85 },
];

export const BASE_PRICES: Record<string, number> = {
  'Paddy (Rice)': 1500,
  'Wheat': 2000,
  'Sugarcane': 800,
  'Cotton': 1200,
  'Mustard': 1000,
  'Maize': 1100,
  'Groundnut': 900,
  'Soybean': 950,
};

export const MOCK_LISTINGS: Listing[] = [
  {
    id: '1',
    farmerId: 'farmer_1',
    cropType: 'Paddy (Rice)',
    residueType: 'Straw / Stubble',
    quantityTons: 50,
    pricePerTon: 1500,
    location: 'Ludhiana, Punjab',
    district: 'Ludhiana',
    state: 'Punjab',
    farmerName: 'Rajinder Singh',
    availableDate: '2024-10-25',
    harvestWindow: { start: '2024-10-20', end: '2024-11-15' },
    quality: 'Premium',
    moistureContent: 10,
    imageUrl: 'https://picsum.photos/seed/paddy/400/300',
    status: 'available',
    bids: [],
    createdAt: '2024-10-10T10:00:00Z',
    carbonPotential: 75,
  },
  {
    id: '2',
    farmerId: 'farmer_2',
    cropType: 'Wheat',
    residueType: 'Husk',
    quantityTons: 120,
    pricePerTon: 2100,
    location: 'Karnal, Haryana',
    district: 'Karnal',
    state: 'Haryana',
    farmerName: 'Amit Kumar',
    availableDate: '2024-11-01',
    harvestWindow: { start: '2024-10-28', end: '2024-11-20' },
    quality: 'Standard',
    moistureContent: 14,
    imageUrl: 'https://picsum.photos/seed/wheat/400/300',
    status: 'available',
    bids: [],
    createdAt: '2024-10-12T10:00:00Z',
    carbonPotential: 180,
  },
  {
    id: '3',
    farmerId: 'farmer_3',
    cropType: 'Sugarcane',
    residueType: 'Bagasse',
    quantityTons: 300,
    pricePerTon: 800,
    location: 'Muzaffarnagar, UP',
    district: 'Muzaffarnagar',
    state: 'Uttar Pradesh',
    farmerName: 'Suresh Patel',
    availableDate: '2024-10-15',
    harvestWindow: { start: '2024-10-10', end: '2024-12-30' },
    quality: 'Mixed',
    moistureContent: 22,
    imageUrl: 'https://picsum.photos/seed/sugar/400/300',
    status: 'bidding',
    bids: [
      {
        id: 'bid_1',
        listingId: '3',
        buyerId: 'buyer_1',
        buyerName: 'Vikram Sharma',
        companyName: 'GreenPower Industries',
        pricePerTon: 850,
        quantity: 300,
        totalAmount: 255000,
        deliveryTerms: 'pickup',
        isForwardContract: false,
        status: 'pending',
        createdAt: '2024-10-14T10:00:00Z',
        expiresAt: '2024-10-21T10:00:00Z',
      }
    ],
    createdAt: '2024-10-08T10:00:00Z',
    carbonPotential: 450,
  },
  {
    id: '4',
    farmerId: 'farmer_4',
    cropType: 'Cotton',
    residueType: 'Stalks',
    quantityTons: 40,
    pricePerTon: 1200,
    location: 'Bathinda, Punjab',
    district: 'Bathinda',
    state: 'Punjab',
    farmerName: 'Harpreet Kaur',
    availableDate: '2024-11-10',
    harvestWindow: { start: '2024-11-05', end: '2024-11-30' },
    quality: 'Standard',
    moistureContent: 15,
    imageUrl: 'https://picsum.photos/seed/cotton/400/300',
    status: 'available',
    bids: [],
    createdAt: '2024-10-15T10:00:00Z',
    carbonPotential: 60,
  },
  {
    id: '5',
    farmerId: 'farmer_5',
    cropType: 'Mustard',
    residueType: 'Stalks',
    quantityTons: 25,
    pricePerTon: 1000,
    location: 'Alwar, Rajasthan',
    district: 'Alwar',
    state: 'Rajasthan',
    farmerName: 'Vikram Singh',
    availableDate: '2024-10-30',
    harvestWindow: { start: '2024-10-25', end: '2024-11-15' },
    quality: 'Premium',
    moistureContent: 11,
    imageUrl: 'https://picsum.photos/seed/mustard/400/300',
    status: 'available',
    bids: [],
    createdAt: '2024-10-18T10:00:00Z',
    carbonPotential: 37.5,
  },
  {
    id: '6',
    farmerId: 'farmer_6',
    cropType: 'Paddy (Rice)',
    residueType: 'Stubble',
    quantityTons: 80,
    pricePerTon: 1400,
    location: 'Sangrur, Punjab',
    district: 'Sangrur',
    state: 'Punjab',
    farmerName: 'Gurpreet Singh',
    availableDate: '2024-10-28',
    harvestWindow: { start: '2024-10-22', end: '2024-11-10' },
    quality: 'Standard',
    moistureContent: 16,
    imageUrl: 'https://picsum.photos/seed/rice2/400/300',
    status: 'available',
    bids: [],
    createdAt: '2024-10-19T10:00:00Z',
    carbonPotential: 120,
  },
];

export const MOCK_EQUIPMENT: Equipment[] = [
  {
    id: 'equip_1',
    name: 'Super Straw Baler',
    type: 'baler',
    description: 'Compact baler suitable for 2-5 acre fields. Creates 20kg rectangular bales.',
    pricePerDay: 2500,
    pricePerTon: 150,
    location: 'Ludhiana, Punjab',
    operatorName: 'Manjeet Singh',
    operatorPhone: '+91 98765 43210',
    available: true,
    imageUrl: 'https://picsum.photos/seed/baler1/400/300',
    rating: 4.8,
  },
  {
    id: 'equip_2',
    name: 'Heavy Duty Rake',
    type: 'rake',
    description: 'Tractor-mounted rake for gathering stubble. Covers 3 acres/hour.',
    pricePerDay: 1500,
    pricePerTon: 80,
    location: 'Karnal, Haryana',
    operatorName: 'Ravi Kumar',
    operatorPhone: '+91 98765 43211',
    available: true,
    imageUrl: 'https://picsum.photos/seed/rake1/400/300',
    rating: 4.5,
  },
  {
    id: 'equip_3',
    name: 'Stubble Collector Pro',
    type: 'collector',
    description: 'All-in-one collection machine. Cuts, gathers, and loads in one pass.',
    pricePerDay: 5000,
    pricePerTon: 200,
    location: 'Patiala, Punjab',
    operatorName: 'Balwinder Singh',
    operatorPhone: '+91 98765 43212',
    available: false,
    imageUrl: 'https://picsum.photos/seed/collector1/400/300',
    rating: 4.9,
  },
  {
    id: 'equip_4',
    name: 'Mini Baler (Self-Operated)',
    type: 'baler',
    description: 'Easy-to-use mini baler for small farmers. Training provided.',
    pricePerDay: 1800,
    pricePerTon: 120,
    location: 'Bathinda, Punjab',
    operatorName: 'Jaspreet Kaur',
    operatorPhone: '+91 98765 43213',
    available: true,
    imageUrl: 'https://picsum.photos/seed/baler2/400/300',
    rating: 4.6,
  },
  {
    id: 'equip_5',
    name: 'Transport Tractor Trolley',
    type: 'transport',
    description: '8-ton capacity trolley for transporting baled residue to collection points.',
    pricePerDay: 2000,
    pricePerTon: 50,
    location: 'Amritsar, Punjab',
    operatorName: 'Hardeep Singh',
    operatorPhone: '+91 98765 43214',
    available: true,
    imageUrl: 'https://picsum.photos/seed/trolley1/400/300',
    rating: 4.7,
  },
];

export const IMPACT_STATS: Stat[] = [
  { label: 'Residue Saved', value: '45,000 Tons', description: 'Diverted from burning this season' },
  { label: 'CO2 Avoided', value: '82,000 Tons', description: 'Equivalent to planting 1M trees' },
  { label: 'Farmer Earnings', value: '₹12.5 Cr', description: 'Additional income generated' },
];

export const CARBON_RATES = {
  CO2_PER_TON_BURNED: 1.5, // tons of CO2 per ton of stubble burned
  CREDIT_PRICE: 15, // USD per ton of CO2
  FARMER_SHARE: 0.80, // 80% to farmer
  BUYER_SHARE: 0.15, // 15% to buyer (ESG credit)
  PLATFORM_SHARE: 0.05, // 5% platform fee
};

export const PLATFORM_FEES = {
  TRANSACTION_COMMISSION: 0.05, // 5%
  EQUIPMENT_COMMISSION: 0.10, // 10%
  CARBON_SHARE: 0.05, // 5%
};

// Mock Forward Contracts - Buyer-initiated future demand
export const MOCK_FORWARD_CONTRACTS = [
  {
    id: 'fc_1',
    buyerId: 'buyer_1',
    buyerName: 'Vikram Sharma',
    companyName: 'GreenPower Industries',
    cropType: 'Paddy (Rice)',
    residueType: 'Straw',
    quantityRequired: 500,
    pricePerTon: 1800,
    deliveryWindow: { start: '2024-11-01', end: '2024-12-15' },
    location: 'Ludhiana',
    state: 'Punjab',
    advancePaymentPercent: 20,
    status: 'open' as const,
    acceptedFarmers: [],
    createdAt: '2024-10-01T10:00:00Z',
    expiresAt: '2024-10-25T23:59:59Z',
  },
  {
    id: 'fc_2',
    buyerId: 'buyer_2',
    buyerName: 'Priya Patel',
    companyName: 'EcoPackage Solutions',
    cropType: 'Wheat',
    residueType: 'Straw',
    quantityRequired: 200,
    pricePerTon: 2200,
    deliveryWindow: { start: '2024-11-10', end: '2024-12-30' },
    location: 'Karnal',
    state: 'Haryana',
    advancePaymentPercent: 15,
    status: 'open' as const,
    acceptedFarmers: [],
    createdAt: '2024-10-05T10:00:00Z',
    expiresAt: '2024-11-01T23:59:59Z',
  },
  {
    id: 'fc_3',
    buyerId: 'buyer_3',
    buyerName: 'Rajesh Kumar',
    companyName: 'BioGas Collective',
    cropType: 'Sugarcane',
    residueType: 'Bagasse',
    quantityRequired: 1000,
    pricePerTon: 950,
    deliveryWindow: { start: '2024-10-20', end: '2025-01-31' },
    location: 'Muzaffarnagar',
    state: 'Uttar Pradesh',
    advancePaymentPercent: 25,
    status: 'partially_filled' as const,
    acceptedFarmers: [
      { farmerId: 'farmer_3', farmerName: 'Suresh Patel', quantity: 200 }
    ],
    createdAt: '2024-10-02T10:00:00Z',
    expiresAt: '2024-10-30T23:59:59Z',
  },
];